# Generated by Django 3.0 on 2019-12-11 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=255, unique=True)),
                ('creator', models.CharField(max_length=255, null=True)),
                ('paradigm', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programmer_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abinitio_app.Company')),
                ('languages', models.ManyToManyField(to='abinitio_app.Language')),
            ],
        ),
    ]
