# Generated by Django 2.2.7 on 2019-12-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abinitio_app', '0002_auto_20191204_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='creator',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='paradigm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programmer',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
