# Generated by Django 2.2.7 on 2019-12-05 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abinitio_app', '0003_auto_20191204_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='comp_name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='lang_name',
        ),
        migrations.RenameField(
            model_name='programmer',
            old_name='name',
            new_name='programmer_name',
        ),
    ]
